Added delete note,section,book
Himasnhu-AT/noterAI pull request #42
Opened 2024-07-25 13:02 UTC by RiyaRaj28

2024-07-25 16:53 UTC, Himasnhu-AT commented on apps/server/backend/src/api/user/book.controller.ts
> +  @Patch(':bookId/:sectionId/:noteId/delete')
Use Delete when you are deleting content

2024-07-25 16:54 UTC, Himasnhu-AT requested changes
resolve error: 

Make @Delete request when api removes something

2024-07-27 04:57 UTC, RiyaRaj28 commented
> @RiyaRaj28 resolve error:
> 
> Make `@ Delete` request when api removes something

Okay, will update them.

2024-07-28 07:15 UTC, RiyaRaj28 commented
> @RiyaRaj28 resolve error:
> 
> Make `@ Delete` request when api removes something

Updated to delete.

2024-07-28 11:32 UTC, Himasnhu-AT approved these changes

2024-07-28 11:32 UTC, merged