Landing page + signup page + errors solved
Himasnhu-AT/noterAI pull request #47
Opened 2024-07-31 06:42 UTC by BhuvanSharma0711

working fine on my device

2024-07-31 12:34 UTC, Himasnhu-AT requested changes
Resolve these comments, along with it, run `pnpm build` locally and ensure it builds

2024-07-31 12:34 UTC, Himasnhu-AT commented on apps/server/backend/src/main.ts
> +    origin: ['http://localhost:3001'],
locally nextjs runs on 3000, update that

2024-07-31 12:34 UTC, Himasnhu-AT commented on apps/web/src/components/Herosection.tsx
> +      <div className="flex justify-center mt-10">
Fields not visible, give z index if hidden by background

2024-07-31 12:34 UTC, Himasnhu-AT commented on apps/web/src/components/Navigationbar.tsx
> +                    <NavbarItem isActive>
keep this filled as a state variable, or remove altogether

isActivate var one...

2024-07-31 12:34 UTC, Himasnhu-AT commented on apps/web/src/components/Signup.tsx
> +              placeholder="Bhuvan"
for placeholder, use fields related to noterai

2024-07-31 19:41 UTC, BhuvanSharma0711 commented
it builds locally now without any errors

2024-08-01 21:16 UTC, Himasnhu-AT approved these changes

2024-08-01 21:17 UTC, merged