verify and login pages
Himasnhu-AT/noterAI pull request #49
Opened 2024-08-02 12:30 UTC by BhuvanSharma0711

Logo transparent is not transparent will solve that is later commits checked build and used a test gmail to send verification code

2024-08-03 17:40 UTC, Himasnhu-AT commented
@BhuvanSharma0711 keep the login and register page the same. Like, keep UI the same. Also, when we click on login, redirect to verify, then dashboard. 

When we click on login, verify the details, and their format. take this as reference: https://github.com/OpenEduHq/WebClient-OpenEdu/blob/main/src/app/(auth)/signin/page.tsx

2024-08-03 17:44 UTC, Himasnhu-AT requested changes
Also complete the comment above

2024-08-03 17:44 UTC, Himasnhu-AT commented on apps/server/backend/src/handlers/email.global.ts
Don't require dotenv package

2024-08-03 17:44 UTC, Himasnhu-AT commented on apps/web/src/app/verify/page.tsx
keep all these page, related to auth under `(auth)/` dir, for example `app/(auth)/verify`

same for login, register, forgot_password

2024-08-05 10:42 UTC, BhuvanSharma0711 commented
so when we click on register we do not go to verify instead we go on sign in and then when we go to sign in then we go to verify??

2024-08-07 17:00 UTC, Himasnhu-AT commented
> so when we click on register we do not go to verify instead we go on sign in and then when we click on sign in then we go to verify?? 

Not like this. For now, as backend isn't deployed, redirect user to verify page when they login or signup, after that redirect to dashboard

> Also I think there is no logic in backend to generate and send verification code when we sign in

The logic is implemented, code is sent via email (using nodemailer)

2024-08-15 08:34 UTC, BhuvanSharma0711 commented
Changes done.

2024-08-18 11:57 UTC, Himasnhu-AT approved these changes

2024-08-18 11:57 UTC, merged